import type { AppNavItem } from './app-navigation.model';

export const APP_NAVIGATION = [
  {
    id: 'dashboard',
    label: 'Pilotage',
    icon: 'pi pi-chart-line',
    route: '/app/dashboard',
    section: 'main',
    desktop: true,
    mobile: true,
    drawer: true,
    ariaLabel: 'Aller au pilotage',
  },
  {
    id: 'opportunities',
    label: 'Opportunités',
    icon: 'pi pi-bullseye',
    route: '/app/opportunities',
    section: 'main',
    desktop: true,
    mobile: true,
    drawer: true,
    ariaLabel: 'Voir les opportunités',
    children: [
      {
        id: 'opportunities-all',
        label: 'Toutes',
        icon: 'pi pi-list',
        route: '/app/opportunities',
        ariaLabel: 'Voir toutes les opportunités',
      },
      {
        id: 'opportunities-new',
        label: 'Nouvelle',
        icon: 'pi pi-plus',
        route: '/app/opportunities/new',
        ariaLabel: 'Créer une nouvelle opportunité',
      },
    ],
  },
  {
    id: 'questions',
    label: 'Questions',
    icon: 'pi pi-comments',
    route: '/app/questions',
    section: 'main',
    desktop: true,
    mobile: true,
    drawer: true,
    ariaLabel: 'Voir les questions',
    children: [
      {
        id: 'questions-radar',
        label: 'Radar',
        icon: 'pi pi-compass',
        route: '/app/questions/radar',
        ariaLabel: 'Ouvrir le radar de questions',
      },
      {
        id: 'questions-training',
        label: 'Training',
        icon: 'pi pi-microphone',
        route: '/app/questions/training',
        ariaLabel: 'Démarrer un entraînement',
      },
    ],
  },
  {
    id: 'actions',
    label: 'Actions',
    icon: 'pi pi-sparkles',
    route: '/app/actions',
    section: 'main',
    desktop: true,
    mobile: true,
    drawer: true,
    badge: '4',
    ariaLabel: 'Voir les actions',
  },
  {
    id: 'opportunity-create',
    label: 'Ajouter opportunité',
    icon: 'pi pi-plus',
    route: '/app/opportunities/new',
    type: 'button',
    section: 'main',
    desktop: true,
    drawer: true,
    ariaLabel: 'Créer une nouvelle opportunité',
  },
  {
    id: 'notifications',
    label: 'Notifications',
    icon: 'pi pi-bell',
    route: '/app/notifications',
    section: 'system',
    desktop: true,
    drawer: true,
    badge: '2',
    ariaLabel: 'Voir les notifications',
  },
  {
    id: 'settings',
    label: 'Settings',
    icon: 'pi pi-cog',
    route: '/app/settings',
    section: 'system',
    desktop: true,
    drawer: true,
    ariaLabel: 'Ouvrir les paramètres',
  },
  {
    id: 'profile',
    label: 'Profil',
    icon: 'pi pi-user',
    route: '/app/profile',
    section: 'system',
    drawer: true,
    ariaLabel: 'Ouvrir le profil',
  },
  {
    id: 'account',
    label: 'Compte',
    icon: 'pi pi-id-card',
    route: '/app/account',
    section: 'system',
    drawer: true,
    ariaLabel: 'Ouvrir le compte',
  },
] as const satisfies readonly AppNavItem[];
